// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		// קבלת כמות הפעמים לבדיקה
		int timesToTest = Integer.parseInt(args[0]);
		// הגדרת כל הערכים הנדרשים
		int roundsOfTest = 0;
		double randValue;
		int aboveHalf = 0;
		int belowHalf = 0;
		double ratio;
		// חישוב כמות החצאים שהרנדום מוציא
		while (roundsOfTest < timesToTest) {
			randValue = Math.random();
			if (randValue > 0.5) {
				aboveHalf++ ;
			}
			else{
				belowHalf++ ;
			}
			roundsOfTest++;
		}
		System.out.println("> 0.5: " + aboveHalf + " times");
		System.out.println("<= 0.5: " + belowHalf + " times");

		// כל עוד אף אחד מהערכים לא שווה אפס נחשב את היחס ונדפיס
		if(aboveHalf != 0 && belowHalf != 0){
			ratio = (double)aboveHalf / belowHalf;
			System.out.println("Ratio: " + ratio);
		}
	}	
}
